name: Build APK & Magisk Release (Auto from Tag)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED so git tags are available

      - name: Fetch tags
        run: git fetch --tags

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        working-directory: ./CompanionApp/installer-app
        run: chmod +x gradlew

      - name: Build Android APK (Release)
        working-directory: ./CompanionApp/installer-app
        run: ./gradlew assembleRelease

      - name: Zip Magisk module
        working-directory: ./MagiskModule
        run: |
          zip -r ../APKInstaller-Magisk.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            CompanionApp/installer-app/build/outputs/apk/release/app-release.apk
            APKInstaller-Magisk.zip

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            app-release.apk
            APKInstaller-Magisk.zip
          generate_release_notes: true

